DFRobotMaqueenPlus.I2CInit()
basic.forever(function () {
    basic.pause(17500)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBA, Color.BLUE)
    basic.pause(300)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBA, Color.OFF)
    basic.pause(300)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBA, Color.PINK)
    basic.pause(300)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBA, Color.OFF)
    basic.pause(1000)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBA, Color.BLUE)
    basic.pause(300)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBA, Color.OFF)
    basic.pause(300)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBA, Color.PINK)
    basic.pause(300)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBA, Color.OFF)
    basic.pause(1000)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBR, Color.WHITH)
    basic.pause(4100)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBA, Color.OFF)
    basic.pause(300)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBA, Color.BLUE)
    basic.pause(300)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBA, Color.OFF)
    basic.pause(300)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBA, Color.PINK)
    basic.pause(300)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBA, Color.OFF)
    basic.pause(1000)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBA, Color.BLUE)
    basic.pause(300)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBA, Color.OFF)
    basic.pause(300)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBA, Color.PINK)
    basic.pause(300)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBA, Color.OFF)
    basic.pause(1000)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBR, Color.WHITH)
    basic.pause(4100)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBA, Color.OFF)
    basic.pause(3500)
})
basic.forever(function () {
    basic.showString("dantzatu nirekin!")
    basic.pause(1000)
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CW, 35)
    basic.pause(100)
    DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CCW, 35)
    basic.pause(100)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    basic.pause(100)
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CCW, 35)
    basic.pause(100)
    DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CW, 35)
    basic.pause(100)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    basic.pause(100)
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CW, 35)
    basic.pause(100)
    DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CCW, 35)
    basic.pause(100)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    basic.pause(800)
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CCW, 35)
    basic.pause(100)
    DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CW, 35)
    basic.pause(100)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    basic.pause(100)
    DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CW, 35)
    basic.pause(100)
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CCW, 35)
    basic.pause(100)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    basic.pause(100)
    DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CCW, 35)
    basic.pause(100)
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CW, 35)
    basic.pause(100)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    basic.pause(100)
    DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CW, 35)
    basic.pause(100)
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CCW, 35)
    basic.pause(100)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    basic.pause(800)
    DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CCW, 35)
    basic.pause(100)
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CW, 35)
    basic.pause(100)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    basic.pause(750)
    DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CCW, 45)
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CW, 45)
    basic.pause(3500)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    basic.pause(900)
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CW, 35)
    basic.pause(100)
    DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CCW, 35)
    basic.pause(100)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    basic.pause(100)
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CCW, 35)
    basic.pause(100)
    DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CW, 35)
    basic.pause(100)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    basic.pause(100)
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CW, 35)
    basic.pause(100)
    DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CCW, 35)
    basic.pause(100)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    basic.pause(800)
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CCW, 35)
    basic.pause(100)
    DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CW, 35)
    basic.pause(100)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    basic.pause(100)
    DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CW, 35)
    basic.pause(100)
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CCW, 35)
    basic.pause(100)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    basic.pause(100)
    DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CCW, 35)
    basic.pause(100)
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CW, 35)
    basic.pause(100)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    basic.pause(100)
    DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CW, 35)
    basic.pause(100)
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CCW, 35)
    basic.pause(100)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    basic.pause(800)
    DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CCW, 35)
    basic.pause(100)
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CW, 35)
    basic.pause(100)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    basic.pause(800)
    DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CCW, 45)
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CW, 45)
    basic.pause(3500)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    basic.pause(1000)
    DFRobotMaqueenPlus.mototRun(Motors.ALL, Dir.CW, 45)
    basic.pause(500)
    basic.showIcon(IconNames.Heart)
    basic.pause(500)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    basic.pause(200)
    DFRobotMaqueenPlus.mototRun(Motors.ALL, Dir.CCW, 45)
    basic.pause(500)
    basic.showIcon(IconNames.SmallHeart)
    basic.pause(500)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    basic.pause(200)
})
