DFRobotMaqueenPlus.I2CInit()
basic.forever(function () {
    basic.showString("dantzatu nirekin!")
    basic.pause(1000)
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CW, 35)
    basic.pause(100)
    DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CCW, 35)
    basic.pause(100)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    basic.pause(100)
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CCW, 35)
    basic.pause(100)
    DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CW, 35)
    basic.pause(100)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    basic.pause(100)
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CW, 35)
    basic.pause(100)
    DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CCW, 35)
    basic.pause(100)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    basic.pause(800)
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CCW, 35)
    basic.pause(100)
    DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CW, 35)
    basic.pause(100)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    basic.pause(100)
    DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CW, 35)
    basic.pause(100)
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CCW, 35)
    basic.pause(100)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    basic.pause(100)
    DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CCW, 35)
    basic.pause(100)
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CW, 35)
    basic.pause(100)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    basic.pause(100)
    DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CW, 35)
    basic.pause(100)
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CCW, 35)
    basic.pause(100)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    basic.pause(800)
    DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CCW, 35)
    basic.pause(100)
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CW, 35)
    basic.pause(100)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    basic.pause(800)
    DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CCW, 35)
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CW, 35)
    basic.pause(4000)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    basic.pause(1000)
})
